version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: mkdir -p my_workspace
      - run: echo "Hello World" > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output
  testa:
    docker:
     - image: circleci/ruby:2.4.1
    steps:
     - attach_workspace:
         at: my_workspace
     - run: cat my_workspace/echo_output
  testb:
    docker:
     - image: circleci/ruby:2.4.1
    steps:
     - attach_workspace:
          at: my_workspace
     - run: |
          # This will fail internallly, we will use SSH to debug and fix
          if [[ $(cat my_worspace/echo_output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
  deploy:
    docker:
     - image: circleci/ruby:2.4.1
    steps:
     - attach_workspace:
        at: my_workspace
     - run: |
          echo "Deploying message"
          cat my_workspace/echo_outpu
     
workflows:
 version: 2
 build_and_test:
  jobs:
    - build
    - testa:
      # Only run the job if build succeeds
        requires:
          - build
    - testb:
      # Only run the job if build succeeds
        requires:
          - build
    - deploy:
        requires:
          - testa
          - testb
        
