version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A First Hello"
      - run: sleep 5
  testa:
    docker:
     - image: circleci/ruby:2.4.1
    steps:
     - checkout
     - run: echo " A more familiar hi"
     - run: sleep 5
 testb:
    docker:
     - image: circleci/ruby:2.4.1
    steps:
     - checkout
     - run: echo " A locallized Salut"
     - run: sleep 5
 deploy:
    docker:
     - image: circleci/ruby:2.4.1
    steps:
     - checkout
     - run: echo " A final Goodbye"
     - run: sleep 5
     
workflows:
 version: 2
 build_and_test:
  jobs:
    - build
    - testa:
      # Only run the job if build succeeds
        requires:
          - build
    - testb:
      # Only run the job if build succeeds
        requires:
          - build
    - deploy:
        requires:
          - testa
          - testb
    
      
